#pragma once
#pragma warning(push) //Hide library warnings
#pragma warning(disable:4996)
#pragma warning(disable:28020)
#pragma warning(disable:26495)
#pragma warning(disable:26451)
#pragma warning(disable:26800)
#pragma warning(disable:28182)
#pragma warning(disable:6001)
#pragma warning(disable:6262)
#pragma warning(disable:6282)
#pragma warning(disable:6308)
#pragma warning(disable:6385)
#pragma warning(disable:6386)
#pragma warning(disable:6387)
#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "tiny_gltf.h"
#pragma warning(pop)